// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSAYBYC-yLmLxhgmKfzP_FINP4f79rxDg',
    appId: '1:542911079019:web:e7382ee95c884d01a3472e',
    messagingSenderId: '542911079019',
    projectId: 'pambe00x',
    authDomain: 'pambe00x.firebaseapp.com',
    databaseURL: 'https://pambe00x-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pambe00x.appspot.com',
    measurementId: 'G-44HE6CWQ4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7kVh_P4fHYQNGXyY_zoQ5IJomVnbb73I',
    appId: '1:542911079019:android:d4ed11ffacb106e5a3472e',
    messagingSenderId: '542911079019',
    projectId: 'pambe00x',
    databaseURL: 'https://pambe00x-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pambe00x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIBpTcSU9ynPvRU27xP73qqM4dyb9GlB8',
    appId: '1:542911079019:ios:f327b5930dc3bec3a3472e',
    messagingSenderId: '542911079019',
    projectId: 'pambe00x',
    databaseURL: 'https://pambe00x-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pambe00x.appspot.com',
    iosBundleId: 'com.example.utsbimbel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIBpTcSU9ynPvRU27xP73qqM4dyb9GlB8',
    appId: '1:542911079019:ios:f327b5930dc3bec3a3472e',
    messagingSenderId: '542911079019',
    projectId: 'pambe00x',
    databaseURL: 'https://pambe00x-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pambe00x.appspot.com',
    iosBundleId: 'com.example.utsbimbel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSAYBYC-yLmLxhgmKfzP_FINP4f79rxDg',
    appId: '1:542911079019:web:00b7818ac5e500e0a3472e',
    messagingSenderId: '542911079019',
    projectId: 'pambe00x',
    authDomain: 'pambe00x.firebaseapp.com',
    databaseURL: 'https://pambe00x-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pambe00x.appspot.com',
    measurementId: 'G-C389SWX810',
  );
}
